const S={
  sb:null,user:null,profile:null,content:[],assignments:[],attempts:[],notifications:[],allowed:[],profiles:[],
  queue:JSON.parse(localStorage.getItem('sh6_queue')||'[]'),deferredInstall:null,currentRun:null,
  authMode:'login',currentPage:'home',subscription:null,importDraft:null,dialogDraft:[],editing:null
};
const titles={home:['Главная','Персональная траектория развития'],training:['Тренировки','Практика по навыкам'],progress:['Мой прогресс','Результаты и история'],notifications:['Уведомления','Новые материалы, задания и дедлайны'],mentor:['Наставник','Команда и зоны развития'],content:['Студия контента','Кейсы, Hard и живые диалоги'],assignments:['Назначения','Задания и дедлайны'],employees:['Сотрудники','Доступы и коды первого входа']};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const jsq=s=>String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'");
const secName=s=>s==='soft'?'Soft Skills':s==='hard'?'Hard Skills':s==='needs'?'Выявление потребности':'Печать';
const initials=s=>String(s||'SH').split(/[\s.]+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2400)}
function randCode(){return String(Math.floor(100000+Math.random()*900000))}
function showModal(html){$('modalCard').innerHTML=html;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function normalizeLogin(s){return String(s||'').trim().toLowerCase()}
function emailFor(login){return normalizeLogin(login).replace(/[^a-z0-9._-]/g,'')+'@skillhub.local'}
function currentConfig(){
  const q=new URLSearchParams(location.search),qUrl=q.get('sburl'),qKey=q.get('sbkey');
  if(qUrl&&qKey){localStorage.setItem('sh6_sb_url',qUrl);localStorage.setItem('sh6_sb_key',qKey);history.replaceState({},'',location.pathname+location.hash)}
  return {url:localStorage.getItem('sh6_sb_url')||window.SKILLHUB_CONFIG?.SUPABASE_URL||'',key:localStorage.getItem('sh6_sb_key')||window.SKILLHUB_CONFIG?.SUPABASE_ANON_KEY||''};
}
function saveSetup(){const url=$('setupUrl').value.trim(),key=$('setupKey').value.trim();if(!/^https:\/\//.test(url)||key.length<40){toast('Проверьте Project URL и anon key');return}localStorage.setItem('sh6_sb_url',url);localStorage.setItem('sh6_sb_key',key);location.reload()}
function initClient(){const c=currentConfig();if(!c.url||!c.key){$('setupView').classList.remove('hidden');return false}S.sb=supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});return true}

function toggleAuthMode(){S.authMode=S.authMode==='login'?'register':'login';const reg=S.authMode==='register';$('authTitle').textContent=reg?'Первый вход':'Давайте потренируемся';$('authText').textContent=reg?'Создайте личный PIN. Сотрудникам нужен код первого входа от наставника.':'Введите корпоративный логин и ваш PIN.';$('inviteWrap').classList.toggle('hidden',!reg);$('pinLabel').textContent=reg?'Придумайте PIN':'PIN';$('pinInput').setAttribute('autocomplete',reg?'new-password':'current-password');$('authBtn').textContent=reg?'Создать профиль':'Войти';$('authModeBtn').textContent=reg?'У меня уже есть PIN':'Первый вход / создать PIN';$('loginError').textContent=''}
async function submitAuth(){const login=normalizeLogin($('loginInput').value),pin=$('pinInput').value,invite=$('inviteInput').value.trim();$('loginError').textContent='';if(!login||pin.length<6){$('loginError').textContent='Введите логин и PIN минимум из 6 символов.';return}try{
  if(S.authMode==='register'){
    const {data,error}=await S.sb.auth.signUp({email:emailFor(login),password:pin,options:{data:{login,invite_code:invite}}});
    if(error)throw error;if(!data.session){throw new Error('В Supabase включено подтверждение e-mail. Отключите Confirm email в Authentication → Providers → Email.')}
  }else{const {error}=await S.sb.auth.signInWithPassword({email:emailFor(login),password:pin});if(error)throw error}
  await afterAuth();
}catch(e){let m=e.message||String(e);if(m.includes('Database error saving new user'))m='Не удалось создать профиль. Проверьте код первого входа. Если это самый первый профиль в новом проекте — код оставьте пустым.';if(m.toLowerCase().includes('invalid login'))m='Неверный логин или PIN.';$('loginError').textContent=m}}
async function afterAuth(){const {data:{user}}=await S.sb.auth.getUser();if(!user)throw new Error('Нет сессии');S.user=user;const {data,error}=await S.sb.from('profiles').select('*').eq('id',user.id).single();if(error)throw error;if(!data.active){await S.sb.auth.signOut();throw new Error('Доступ к SkillHub отключён наставником.')}S.profile=data;localStorage.setItem('sh6_profile',JSON.stringify(data));enterApp();await syncAll()}
async function logout(){if(S.sb)await S.sb.auth.signOut();if(S.subscription)S.sb.removeChannel(S.subscription);S.user=null;S.profile=null;$('appView').classList.add('hidden');$('loginView').classList.remove('hidden');$('profileMenu').classList.add('hidden')}
function enterApp(){$('setupView').classList.add('hidden');$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('profileName').textContent=S.profile.name||S.profile.login;$('roleLabel').textContent=S.profile.role==='mentor'?'Наставник':'Сотрудник';$('avatar').textContent=initials(S.profile.name||S.profile.login);document.querySelectorAll('.mentor-only').forEach(x=>x.classList.toggle('hidden',S.profile.role!=='mentor'));go(S.profile.role==='mentor'?'mentor':'home');subscribeRealtime()}

function go(page){S.currentPage=page;document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));const el=$('page-'+page);if(el)el.classList.remove('hidden');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===page));if(titles[page]){$('pageTitle').textContent=titles[page][0];$('pageSub').textContent=titles[page][1]}render(page)}
function render(p){({home:renderHome,training:renderTraining,progress:renderProgress,notifications:renderNotifications,mentor:renderMentor,content:renderContent,assignments:renderAssignments,employees:renderEmployees}[p]||(()=>{}))()}
function renderCurrent(){render(S.currentPage)}
function updateNetwork(){const on=navigator.onLine;$('offlineBanner').classList.toggle('hidden',on);$('syncDot').classList.toggle('off',!on);$('syncLabel').textContent=on?(S.queue.length?'Ожидает отправки':'Синхронизировано'):'Офлайн';$('syncSub').textContent=on?(S.queue.length?`${S.queue.length} в очереди`:'облачная база'):`${S.queue.length} в очереди`}
function normalizeContent(r){return {...r,...(r.payload||{})}}
async function syncAll(manual=false){updateNetwork();if(!S.user)return;if(navigator.onLine)await flushQueue();try{
  const qs=[S.sb.from('content').select('*').order('updated_at',{ascending:false}),S.sb.from('assignments').select('*').order('created_at',{ascending:false}),S.sb.from('attempts').select('*').order('created_at',{ascending:true}),S.sb.from('notifications').select('*').order('created_at',{ascending:true})];
  const [c,a,t,n]=await Promise.all(qs);for(const r of [c,a,t,n])if(r.error)throw r.error;S.content=(c.data||[]).map(normalizeContent);S.assignments=a.data||[];S.attempts=t.data||[];S.notifications=n.data||[];
  if(S.profile.role==='mentor'){const [al,pr]=await Promise.all([S.sb.from('allowed_logins').select('*').order('login'),S.sb.from('profiles').select('*').order('login')]);if(al.error)throw al.error;if(pr.error)throw pr.error;S.allowed=al.data||[];S.profiles=pr.data||[]}
  localStorage.setItem('sh6_cache_'+S.profile.login,JSON.stringify({content:S.content,assignments:S.assignments,attempts:S.attempts,notifications:S.notifications,allowed:S.allowed,profiles:S.profiles}));renderUnread();renderCurrent();if(manual)toast('Данные обновлены');
}catch(e){const c=JSON.parse(localStorage.getItem('sh6_cache_'+S.profile.login)||'null');if(c){Object.assign(S,c);renderUnread();renderCurrent()}if(manual)toast('Нет связи с базой — показана локальная копия')}}
function subscribeRealtime(){if(S.subscription)S.sb.removeChannel(S.subscription);S.subscription=S.sb.channel('skillhub-live').on('postgres_changes',{event:'*',schema:'public',table:'content'},()=>onCloudChange('Обновлены материалы')).on('postgres_changes',{event:'*',schema:'public',table:'assignments'},()=>onCloudChange('Обновлены задания')).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications'},p=>onCloudChange(p.new?.title||'Новое уведомление')).subscribe()}
let refreshTimer=null;function onCloudChange(text){clearTimeout(refreshTimer);refreshTimer=setTimeout(async()=>{await syncAll();if('Notification'in window&&Notification.permission==='granted')new Notification('SkillHub',{body:text,icon:'./icon-192.png'});toast(text)},500)}
function renderUnread(){const n=S.notifications.filter(x=>!x.read).length;$('bellBadge').textContent=n;$('bellBadge').classList.toggle('hidden',!n);if(navigator.setAppBadge){if(n)navigator.setAppBadge(n).catch(()=>{});else navigator.clearAppBadge?.().catch(()=>{})}}
function recordAttempt(a){const row={id:crypto.randomUUID(),user_id:S.user.id,login:S.profile.login,created_at:new Date().toISOString(),...a};S.attempts.push(row);S.queue.push(row);localStorage.setItem('sh6_queue',JSON.stringify(S.queue));updateNetwork();if(navigator.onLine)flushQueue()}
async function flushQueue(){if(!S.queue.length||!navigator.onLine)return;const copy=[...S.queue];const {error}=await S.sb.from('attempts').insert(copy);if(!error){S.queue=[];localStorage.setItem('sh6_queue','[]');updateNetwork()}}

function assignmentHtml(x){const due=x.due?new Date(x.due+'T12:00:00'):null,days=due?Math.ceil((due-new Date())/86400000):null;return `<div class="assignment"><div><b>${esc(x.title)}</b><div class="meta">${x.section?secName(x.section):''}${x.topic?' · '+esc(x.topic):''}${x.due?' · до '+esc(x.due):''}${days!==null&&days<=1?' · ⏰ скоро':''}</div></div><div class="actions"><span class="pill">${x.target}%+</span><button class="btn secondary" onclick="startAssignment('${x.id}')">Начать</button></div></div>`}
function trainingCards(){return `<div class="grid4"><div class="card train-card"><div class="icon">💬</div><h3>Soft Skills</h3><p>Присоединение, негатив, отказ и формулировки.</p><button class="btn primary" onclick="openSection('soft')">Тренировать</button></div><div class="card train-card"><div class="icon">🧠</div><h3>Hard Skills</h3><p>Решение реальных клиентских кейсов по продуктам.</p><button class="btn primary" onclick="openSection('hard')">Тренировать</button></div><div class="card train-card"><div class="icon">🎯</div><h3>Потребность</h3><p>Вопросы, критерии и живые диалоги.</p><button class="btn primary" onclick="openSection('needs')">Тренировать</button></div><div class="card train-card"><div class="icon">⌨️</div><h3>Печать</h3><p>Минутная тренировка скорости и точности.</p><button class="btn primary" onclick="startTyping()">Начать</button></div></div>`}
function avgSection(sec){const a=S.attempts.filter(x=>x.login===S.profile.login&&x.section===sec);return a.length?Math.round(a.reduce((s,x)=>s+Number(x.score),0)/a.length):null}
function renderHome(){const ass=S.assignments.filter(x=>x.status==='active');$('page-home').innerHTML=`<div class="grid4"><div class="card kpi"><small>Soft Skills</small><strong>${avgSection('soft')===null?'—':avgSection('soft')+'%'}</strong></div><div class="card kpi"><small>Hard Skills</small><strong>${avgSection('hard')===null?'—':avgSection('hard')+'%'}</strong></div><div class="card kpi"><small>Потребность</small><strong>${avgSection('needs')===null?'—':avgSection('needs')+'%'}</strong></div><div class="card kpi"><small>Активные задания</small><strong>${ass.length}</strong></div></div><div class="section-title"><h2>📌 Мои задания</h2></div><div class="card">${ass.length?ass.map(assignmentHtml).join(''):'<div class="muted">Активных заданий пока нет.</div>'}</div><div class="section-title"><h2>Быстрый старт</h2></div>${trainingCards()}<div class="section-title"><h2>📲 На телефоне</h2></div><div class="card mobile-install"><h3>Установите SkillHub</h3><p class="muted">После установки появится отдельная иконка. Загруженные тренировки сохраняются для офлайн-работы.</p><div class="actions"><button class="btn primary" onclick="installApp()">Установить / инструкция</button><button class="btn secondary" onclick="enableNotifications()">🔔 Уведомления</button></div></div>`}
function renderTraining(){$('page-training').innerHTML=trainingCards()+`<div class="section-title"><h2>Библиотека</h2><span class="muted small">${S.content.filter(x=>x.status==='published').length} материалов</span></div><div class="card">${['soft','hard','needs'].map(sec=>`<div class="assignment"><div><b>${secName(sec)}</b><div class="meta">${S.content.filter(x=>x.section===sec&&x.status==='published').length} материалов</div></div><button class="btn secondary" onclick="openSection('${sec}')">Открыть</button></div>`).join('')}</div>`}
function openSection(sec){const arr=S.content.filter(x=>x.section===sec&&x.status==='published'),topics=[...new Set(arr.map(x=>x.topic))];showModal(`<div class="modal-head"><div><h2>${secName(sec)}</h2><div class="muted small">Выберите тему или материал</div></div><button class="btn secondary" onclick="closeModal()">✕</button></div><div class="topic-grid">${topics.map(t=>`<button class="topic" onclick="closeModal();startTopic('${sec}','${jsq(t)}')">${esc(t)}<small>${arr.filter(x=>x.topic===t).length} материалов</small></button>`).join('')}</div><div class="section-title"><h2>Материалы</h2></div>${arr.map(x=>`<div class="content-row"><div><span class="pill">${x.type==='dialogue'?'Диалог':x.type==='hardcase'?'Hard-кейс':'Кейс'}</span><b>${esc(x.title||x.question)}</b><div class="meta">${esc(x.topic)}</div></div><button class="btn secondary" onclick="closeModal();startContent('${x.id}')">Начать</button></div>`).join('')||'<p class="muted">Пока пусто.</p>'}`)}
function startTopic(sec,topic){const q=S.content.filter(x=>x.status==='published'&&x.section===sec&&x.topic===topic&&x.type!=='dialogue');if(q.length)startQuiz(q,sec,topic);else{const d=S.content.find(x=>x.status==='published'&&x.section===sec&&x.topic===topic&&x.type==='dialogue');if(d)startDialogue(d)}}
function startContent(id){const x=S.content.find(c=>c.id===id);if(!x)return;x.type==='dialogue'?startDialogue(x):startQuiz([x],x.section,x.topic)}
function startAssignment(id){const a=S.assignments.find(x=>x.id===id);if(!a)return;a.content_id?startContent(a.content_id):startTopic(a.section,a.topic)}
function goRun(){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$('page-run').classList.remove('hidden');$('pageTitle').textContent='Тренировка';$('pageSub').textContent='Практика'}
function startQuiz(items,sec,topic){S.currentRun={type:'quiz',items:[...items].sort(()=>Math.random()-.5),i:0,score:0,sec,topic};goRun();renderQuiz()}
function renderQuiz(){const r=S.currentRun;if(r.i>=r.items.length){finishQuiz();return}const x=r.items[r.i];$('page-run').innerHTML=`<div class="card" style="max-width:850px;margin:auto"><div class="actions" style="justify-content:space-between"><button class="btn secondary" onclick="go('training')">← Выйти</button><b>${esc(x.topic)}</b><span class="muted small">${r.i+1}/${r.items.length}</span></div><div class="progress"><span style="width:${r.i/r.items.length*100}%"></span></div><div class="question">${esc(x.question)}</div><div class="options">${(x.answers||[]).map((a,i)=>`<button class="option" onclick="answerQuiz(${i})">${esc(a)}</button>`).join('')}</div><div id="runFeedback"></div></div>`}
function answerQuiz(i){const r=S.currentRun,x=r.items[r.i];document.querySelectorAll('.option').forEach((b,k)=>{b.disabled=true;if(k===Number(x.correct))b.classList.add('correct');if(k===i&&k!==Number(x.correct))b.classList.add('wrong')});if(i===Number(x.correct))r.score++;$('runFeedback').innerHTML=`<div class="explain">${esc(x.explanation||'')}</div><div class="actions" style="justify-content:flex-end;margin-top:12px"><button class="btn primary" onclick="S.currentRun.i++;renderQuiz()">Дальше</button></div>`}
function finishQuiz(){const r=S.currentRun,p=Math.round(r.score/r.items.length*100);recordAttempt({section:r.sec,topic:r.topic,score:p,type:'quiz',cpm:0});$('page-run').innerHTML=`<div class="card" style="max-width:650px;margin:auto;text-align:center"><strong style="font-size:52px">${p}%</strong><h2>Тренировка завершена</h2><p class="muted">${r.score} из ${r.items.length} правильных решений</p><button class="btn primary" onclick="go('training')">Готово</button></div>`}
function startDialogue(x){S.currentRun={type:'dialogue',x,i:0,score:0};goRun();renderDialogue()}
function renderDialogue(){const r=S.currentRun,x=r.x;if(r.i>=(x.steps||[]).length){finishDialogue();return}const s=x.steps[r.i];$('page-run').innerHTML=`<div class="dialogue"><div class="card"><div class="actions" style="justify-content:space-between"><button class="btn secondary" onclick="go('training')">← Выйти</button><b>${esc(x.title)}</b><span class="muted small">${r.i+1}/${x.steps.length}</span></div><div class="bubble client"><b>Клиент</b><br>${esc(s.client)}</div><div class="muted small" style="margin:14px 0 8px">Что ответит сотрудник?</div><div class="options">${s.options.map((a,i)=>`<button class="option" onclick="answerDialogue(${i})">${esc(a)}</button>`).join('')}</div><div id="runFeedback"></div></div></div>`}
function answerDialogue(i){const r=S.currentRun,s=r.x.steps[r.i];document.querySelectorAll('.option').forEach((b,k)=>{b.disabled=true;if(k===Number(s.correct))b.classList.add('correct');if(k===i&&k!==Number(s.correct))b.classList.add('wrong')});if(i===Number(s.correct))r.score++;$('runFeedback').innerHTML=`<div class="explain">${esc(s.explanation||'')}</div>${s.next_client?`<div class="bubble client"><b>Клиент</b><br>${esc(s.next_client)}</div>`:''}<div class="actions" style="justify-content:flex-end;margin-top:12px"><button class="btn primary" onclick="S.currentRun.i++;renderDialogue()">Продолжить</button></div>`}
function finishDialogue(){const r=S.currentRun,p=Math.round(r.score/r.x.steps.length*100);recordAttempt({section:r.x.section,topic:r.x.topic,score:p,type:'dialogue',cpm:0});$('page-run').innerHTML=`<div class="card" style="max-width:650px;margin:auto;text-align:center"><strong style="font-size:52px">${p}%</strong><h2>Диалог завершён</h2><p class="muted">${r.score} из ${r.x.steps.length} правильных решений</p><button class="btn primary" onclick="go('training')">Готово</button></div>`}
let typingInt=null;function startTyping(){S.currentRun={start:0,text:'Понимаю, что ситуация для вас важна. Давайте я проверю информацию и подскажу, какие варианты доступны сейчас.'};goRun();$('page-run').innerHTML=`<div class="card" style="max-width:850px;margin:auto"><div class="actions" style="justify-content:space-between"><button class="btn secondary" onclick="go('training')">← Выйти</button><b>Скорость печати</b><span id="typingTimer" class="muted">60 сек.</span></div><div class="explain" style="font-size:18px;margin:15px 0">${esc(S.currentRun.text)}</div><textarea id="typingBox" placeholder="Начните печатать…" oninput="typingInput()"></textarea><div id="typingStats" class="grid3" style="margin-top:12px"></div></div>`;typingInput()}
function typingInput(){const b=$('typingBox');if(!b)return;const v=b.value,r=S.currentRun;if(!r.start&&v.length){r.start=Date.now();typingInt=setInterval(updateTyping,500)}updateTyping()}
function updateTyping(){const b=$('typingBox');if(!b)return;const r=S.currentRun,v=b.value,e=r.start?Math.max((Date.now()-r.start)/1000,1):1,left=Math.max(0,60-Math.floor(e));let m=0;for(let i=0;i<v.length;i++)if(v[i]===r.text[i])m++;const ac=v.length?Math.round(m/v.length*100):100,cpm=Math.round(v.length/(e/60));$('typingTimer').textContent=left+' сек.';$('typingStats').innerHTML=`<div class="card kpi"><small>Скорость</small><strong>${cpm}</strong><span class="muted small">зн./мин</span></div><div class="card kpi"><small>Точность</small><strong>${ac}%</strong></div><div class="card kpi"><small>Знаков</small><strong>${v.length}</strong></div>`;if(left<=0){clearInterval(typingInt);b.disabled=true;recordAttempt({section:'typing',topic:'60 секунд',score:ac,type:'typing',cpm});toast('Результат сохранён')}}
function renderProgress(){const a=S.attempts.filter(x=>x.login===S.profile.login).slice().reverse();$('page-progress').innerHTML=`<div class="grid3"><div class="card kpi"><small>Попыток</small><strong>${a.length}</strong></div><div class="card kpi"><small>Средний результат</small><strong>${a.length?Math.round(a.reduce((s,x)=>s+Number(x.score),0)/a.length)+'%':'—'}</strong></div><div class="card kpi"><small>Последняя активность</small><strong style="font-size:17px">${a[0]?new Date(a[0].created_at).toLocaleDateString('ru-RU'):'—'}</strong></div></div><div class="section-title"><h2>История</h2></div><div class="card table-wrap"><table class="table"><thead><tr><th>Дата</th><th>Раздел</th><th>Тема</th><th>Результат</th></tr></thead><tbody>${a.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('ru-RU')}</td><td>${secName(x.section)}</td><td>${esc(x.topic)}</td><td><span class="pill ${Number(x.score)>=90?'good':Number(x.score)>=75?'warn':'bad'}">${x.score}%</span></td></tr>`).join('')}</tbody></table></div>`}
async function markAllRead(){const ids=S.notifications.filter(x=>!x.read).map(x=>x.id);if(!ids.length)return;const {error}=await S.sb.from('notifications').update({read:true}).in('id',ids);if(!error){S.notifications.forEach(n=>n.read=true);renderUnread();renderNotifications()}}
function renderNotifications(){$('page-notifications').innerHTML=`<div class="actions" style="justify-content:flex-end"><button class="btn secondary" onclick="markAllRead()">Прочитать всё</button></div><div class="card" style="margin-top:10px">${S.notifications.length?S.notifications.slice().reverse().map(n=>`<div class="notification"><div><b>${n.read?'':'● '}${esc(n.title)}</b><div class="meta">${esc(n.body)} · ${new Date(n.created_at).toLocaleString('ru-RU')}</div></div></div>`).join(''):'<div class="muted">Уведомлений нет.</div>'}</div>`}

function teamRows(){const active=S.allowed.filter(x=>x.active&&x.role==='employee');return active.map(u=>{const a=S.attempts.filter(x=>x.login===u.login),avg=sec=>{const q=a.filter(x=>x.section===sec);return q.length?Math.round(q.reduce((s,x)=>s+Number(x.score),0)/q.length):0};return {...u,soft:avg('soft'),hard:avg('hard'),needs:avg('needs'),attempts:a.length}})}
function renderMentor(){const u=teamRows(),avg=k=>u.length?Math.round(u.reduce((s,x)=>s+x[k],0)/u.length):0;$('page-mentor').innerHTML=`<div class="grid4"><div class="card kpi"><small>Команда</small><strong>${u.length}</strong><span class="muted small">активных сотрудников</span></div><div class="card kpi"><small>Soft</small><strong>${avg('soft')}%</strong></div><div class="card kpi"><small>Hard</small><strong>${avg('hard')}%</strong></div><div class="card kpi"><small>Потребность</small><strong>${avg('needs')}%</strong></div></div><div class="section-title"><h2>Команда</h2></div><div class="card table-wrap"><table class="table"><thead><tr><th>Логин</th><th>Soft</th><th>Hard</th><th>Потребность</th><th>Попыток</th></tr></thead><tbody>${u.map(x=>`<tr><td>${esc(x.login)}</td><td>${x.soft}%</td><td>${x.hard}%</td><td>${x.needs}%</td><td>${x.attempts}</td></tr>`).join('')}</tbody></table></div>`}

let contentTab='library';function renderContent(){$('page-content').innerHTML=`<div class="tabs"><button class="tab ${contentTab==='library'?'active':''}" onclick="contentTab='library';renderContent()">Библиотека</button><button class="tab ${contentTab==='create'?'active':''}" onclick="contentTab='create';renderContent()">Создать</button><button class="tab ${contentTab==='import'?'active':''}" onclick="contentTab='import';renderContent()">Импорт Excel</button></div><div id="contentPane"></div>`;contentTab==='library'?renderContentLibrary():contentTab==='create'?renderCreateContent():renderImportPane()}
function renderContentLibrary(){$('contentPane').innerHTML=`<div class="toolbar"><span class="muted small">${S.content.length} материалов</span><div><button class="btn secondary" onclick="exportExcel()">⬇ Экспорт Excel</button></div></div><div class="card" style="margin-top:10px">${S.content.map(x=>`<div class="content-row"><div><span class="pill ${x.status==='published'?'status-published':'status-draft'}">${x.status==='published'?'Опубликовано':'Черновик'}</span> <span class="pill">${x.type==='dialogue'?'Диалог':x.type==='hardcase'?'Hard-кейс':'Кейс'}</span><b>${esc(x.title||x.question)}</b><div class="meta">${secName(x.section)} · ${esc(x.topic)}</div></div><div class="actions"><button class="btn secondary" onclick="editContent('${x.id}')">Изменить</button><button class="btn danger" onclick="deleteContent('${x.id}')">Удалить</button></div></div>`).join('')||'<div class="muted">Материалов нет.</div>'}</div>`}
function renderCreateContent(){$('contentPane').innerHTML=`<div class="grid3"><button class="topic" onclick="openCaseEditor('quiz')">✅ Обычный кейс<small>Soft / Hard / потребность</small></button><button class="topic" onclick="openCaseEditor('hardcase')">🧠 Hard-кейс<small>Клиентская ситуация → решение</small></button><button class="topic" onclick="openDialogueEditor()">💬 Живой диалог<small>Несколько последовательных шагов</small></button></div>`}
function renderImportPane(){$('contentPane').innerHTML=`<div class="import-box"><h3>Импорт из Excel</h3><p>Кейсы, диалоги, сотрудники и назначения можно загрузить одним файлом.</p><div class="actions" style="justify-content:center"><a class="btn secondary" href="./SkillHub_Шаблон_импорта_кейсов.xlsx" download>⬇ Скачать шаблон</a><label class="btn primary">Выбрать Excel<input type="file" accept=".xlsx" class="hidden" onchange="previewExcel(event)"></label></div></div><div id="importPreview"></div>`}
function parseWorkbook(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>{try{const wb=XLSX.read(fr.result,{type:'array'}),out={};for(const n of wb.SheetNames)out[n]=XLSX.utils.sheet_to_json(wb.Sheets[n],{defval:''});resolve(out)}catch(e){reject(e)}};fr.onerror=reject;fr.readAsArrayBuffer(file)})}
async function previewExcel(ev){try{const sheets=await parseWorkbook(ev.target.files[0]);const cases=(sheets['Кейсы']||[]).filter(r=>String(r['Вопрос']||'').trim()),dialogs=(sheets['Диалоги']||[]).filter(r=>String(r['ID диалога']||'').trim()),employees=(sheets['Сотрудники']||[]).filter(r=>String(r['Логин']||'').trim()),assignments=(sheets['Назначения']||[]).filter(r=>String(r['Название']||'').trim());S.importDraft={sheets,cases,dialogs,employees,assignments};$('importPreview').innerHTML=`<div class="card" style="margin-top:12px"><h3>Предпросмотр</h3><div class="grid4"><div class="kpi"><small>Кейсы</small><strong>${cases.length}</strong></div><div class="kpi"><small>Диалоги</small><strong>${dialogs.length}</strong></div><div class="kpi"><small>Сотрудники</small><strong>${employees.length}</strong></div><div class="kpi"><small>Назначения</small><strong>${assignments.length}</strong></div></div><div class="actions" style="justify-content:flex-end;margin-top:12px"><button class="btn primary" onclick="commitExcel()">Импортировать</button></div></div>`}catch(e){$('importPreview').innerHTML='<div class="explain">Не удалось прочитать Excel. Используйте шаблон SkillHub.</div>'}}
function yn(x){return ['да','yes','true','1'].includes(String(x).trim().toLowerCase())}
async function notifyRecipients(title,body,recipients,kind='content'){let logs=recipients.includes('ALL')?S.allowed.filter(x=>x.active&&x.role==='employee').map(x=>x.login):recipients;logs=[...new Set(logs)];if(!logs.length)return;const rows=logs.map(login=>({login,title,body,kind,read:false}));await S.sb.from('notifications').insert(rows)}
async function commitExcel(){if(!S.importDraft)return;const {sheets,cases,dialogs,employees,assignments}=S.importDraft;const generated=[];try{
  for(const r of employees){const login=normalizeLogin(r['Логин']);if(!login)continue;const existing=S.allowed.find(x=>x.login===login),claimed=!!existing?.claimed_user_id;let code='';if(!claimed)code=randCode();const role=String(r['Роль']||'').toLowerCase().startsWith('настав')?'mentor':'employee';const {error}=await S.sb.rpc('mentor_upsert_allowed_user',{p_login:login,p_name:String(r['Имя']||login),p_role:role,p_group_name:String(r['Группа']||'Группа'),p_active:String(r['Статус']||'active').toLowerCase()!=='inactive',p_invite_code:code||null});if(error)throw error;if(code)generated.push([login,code])}
  for(const r of cases){const answers=[1,2,3,4].map(i=>String(r['Ответ '+i]||'').trim());if(answers.some(x=>!x))continue;const audience=String(r['Кому']||'ALL').split(',').map(x=>x.trim()).filter(Boolean);const row={type:String(r['Тип']||'quiz'),status:String(r['Статус']||'draft'),section:String(r['Раздел']||'soft'),topic:String(r['Тема']||'Общий'),difficulty:String(r['Сложность']||'Средний'),title:String(r['Заголовок']||''),payload:{question:String(r['Вопрос']||''),answers,correct:Math.max(0,Number(r['Правильный ответ']||1)-1),explanation:String(r['Объяснение']||'')},audience,created_by:S.user.id,updated_at:new Date().toISOString()};if(String(r['ID']||'').match(/^[0-9a-f-]{36}$/i))row.id=r['ID'];const {data,error}=await S.sb.from('content').upsert(row).select().single();if(error)throw error;if(row.status==='published'&&yn(r['Уведомить']))await notifyRecipients('Новый материал',row.title||row.payload.question.slice(0,80),audience)}
  const stepRows=sheets['Шаги диалогов']||[];for(const r of dialogs){const did=String(r['ID диалога']).trim(),steps=stepRows.filter(s=>String(s['ID диалога']).trim()===did).sort((a,b)=>Number(a['Шаг'])-Number(b['Шаг'])).map(s=>({client:String(s['Реплика клиента']||''),options:[1,2,3].map(i=>String(s['Ответ '+i]||'')),correct:Math.max(0,Number(s['Правильный ответ']||1)-1),next_client:String(s['Следующая реплика клиента']||''),explanation:String(s['Объяснение']||'')}));if(!steps.length)continue;const audience=String(r['Кому']||'ALL').split(',').map(x=>x.trim()).filter(Boolean);const row={type:'dialogue',status:String(r['Статус']||'draft'),section:String(r['Раздел']||'needs'),topic:String(r['Тема']||'Общий'),difficulty:'Средний',title:String(r['Название']||did),payload:{description:String(r['Описание']||''),steps},audience,created_by:S.user.id,updated_at:new Date().toISOString()};if(did.match(/^[0-9a-f-]{36}$/i))row.id=did;const {error}=await S.sb.from('content').upsert(row);if(error)throw error;if(row.status==='published'&&yn(r['Уведомить']))await notifyRecipients('Новый диалог',row.title,audience)}
  for(const r of assignments){const rec=String(r['Кому']||'ALL').split(',').map(x=>x.trim()).filter(Boolean);const row={title:String(r['Название']),content_id:String(r['ID материала']||'').match(/^[0-9a-f-]{36}$/i)?String(r['ID материала']):null,section:String(r['Раздел']||''),topic:String(r['Тема']||''),due:String(r['Дедлайн']||'')||null,target:Number(r['Минимум %']||90),recipients:rec,status:String(r['Статус']||'active'),created_by:S.user.id};const {error}=await S.sb.from('assignments').insert(row);if(error)throw error;if(yn(r['Уведомить']))await notifyRecipients('Новое задание',`${row.title}${row.due?' · до '+row.due:''}`,rec,'assignment')}
  await syncAll();toast('Импорт завершён');if(generated.length)showCodes(generated,'Коды для новых сотрудников');contentTab='library';renderContent();
}catch(e){console.error(e);toast('Ошибка импорта: '+(e.message||e))}}
function exportExcel(){const wb=XLSX.utils.book_new();const cases=[],dialogs=[],steps=[];for(const x of S.content){if(x.type==='dialogue'){dialogs.push({'ID диалога':x.id,'Статус':x.status,'Раздел':x.section,'Тема':x.topic,'Название':x.title,'Описание':x.description||'','Кому':(x.audience||['ALL']).join(', '),'Уведомить':'Нет'});(x.steps||[]).forEach((s,i)=>steps.push({'ID диалога':x.id,'Шаг':i+1,'Реплика клиента':s.client,'Ответ 1':s.options?.[0]||'','Ответ 2':s.options?.[1]||'','Ответ 3':s.options?.[2]||'','Правильный ответ':Number(s.correct)+1,'Следующая реплика клиента':s.next_client||'','Объяснение':s.explanation||''}))}else cases.push({'ID':x.id,'Статус':x.status,'Раздел':x.section,'Тема':x.topic,'Сложность':x.difficulty,'Тип':x.type,'Заголовок':x.title,'Вопрос':x.question,'Ответ 1':x.answers?.[0]||'','Ответ 2':x.answers?.[1]||'','Ответ 3':x.answers?.[2]||'','Ответ 4':x.answers?.[3]||'','Правильный ответ':Number(x.correct)+1,'Объяснение':x.explanation||'','Кому':(x.audience||['ALL']).join(', '),'Уведомить':'Нет'})}XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(cases),'Кейсы');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(dialogs),'Диалоги');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(steps),'Шаги диалогов');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(S.allowed.map(x=>({'Логин':x.login,'Имя':x.name,'Роль':x.role==='mentor'?'Наставник':'Сотрудник','Группа':x.group_name,'Статус':x.active?'active':'inactive'}))),'Сотрудники');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(S.assignments.map(x=>({'ID':x.id,'Название':x.title,'Раздел':x.section,'Тема':x.topic,'ID материала':x.content_id||'','Кому':(x.recipients||['ALL']).join(', '),'Дедлайн':x.due||'','Минимум %':x.target,'Уведомить':'Нет','Статус':x.status}))),'Назначения');XLSX.writeFile(wb,'SkillHub_export.xlsx')}
function openCaseEditor(type,x=null){S.editing=x?.id||null;showModal(`<div class="modal-head"><h2>${x?'Редактировать':type==='hardcase'?'Новый Hard-кейс':'Новый кейс'}</h2><button class="btn secondary" onclick="closeModal()">✕</button></div><div class="form-grid"><div class="field"><label>Раздел</label><select id="ecSec"><option value="soft">Soft</option><option value="hard">Hard</option><option value="needs">Потребность</option></select></div><div class="field"><label>Тема</label><input id="ecTopic"></div><div class="field"><label>Статус</label><select id="ecStatus"><option value="draft">Черновик</option><option value="published">Опубликовать</option></select></div><div class="field"><label>Сложность</label><select id="ecDiff"><option>Лёгкий</option><option>Средний</option><option>Сложный</option></select></div><div class="field full"><label>Заголовок</label><input id="ecTitle"></div><div class="field full"><label>Вопрос / ситуация</label><textarea id="ecQ"></textarea></div>${[1,2,3,4].map(i=>`<div class="field"><label>Ответ ${i}</label><textarea id="ecA${i}"></textarea></div>`).join('')}<div class="field"><label>Правильный ответ</label><select id="ecCorrect">${[1,2,3,4].map(i=>`<option value="${i-1}">${i}</option>`).join('')}</select></div><div class="field"><label>Кому</label><input id="ecAudience" value="ALL"></div><div class="field full"><label>Объяснение</label><textarea id="ecExpl"></textarea></div></div><div class="actions" style="justify-content:flex-end;margin-top:13px"><button class="btn primary" onclick="saveCaseEditor('${type}')">Сохранить</button></div>`);$('ecSec').value=x?.section|| (type==='hardcase'?'hard':'soft');$('ecTopic').value=x?.topic||'';$('ecStatus').value=x?.status||'draft';$('ecDiff').value=x?.difficulty||'Средний';$('ecTitle').value=x?.title||'';$('ecQ').value=x?.question||'';[1,2,3,4].forEach((i,k)=>$('ecA'+i).value=x?.answers?.[k]||'');$('ecCorrect').value=String(x?.correct??0);$('ecAudience').value=(x?.audience||['ALL']).join(', ');$('ecExpl').value=x?.explanation||''}
async function saveCaseEditor(type){const answers=[1,2,3,4].map(i=>$('ecA'+i).value.trim());if(!$('ecTopic').value.trim()||!$('ecQ').value.trim()||answers.some(x=>!x)){toast('Заполните тему, вопрос и 4 ответа');return}const row={type,section:$('ecSec').value,topic:$('ecTopic').value.trim(),status:$('ecStatus').value,difficulty:$('ecDiff').value,title:$('ecTitle').value.trim(),payload:{question:$('ecQ').value.trim(),answers,correct:Number($('ecCorrect').value),explanation:$('ecExpl').value.trim()},audience:$('ecAudience').value.split(',').map(x=>x.trim()).filter(Boolean),created_by:S.user.id,updated_at:new Date().toISOString()};if(S.editing)row.id=S.editing;const {data,error}=await S.sb.from('content').upsert(row).select().single();if(error){toast(error.message);return}if(row.status==='published')await notifyRecipients('Новый материал',row.title||row.payload.question.slice(0,80),row.audience);closeModal();await syncAll();contentTab='library';renderContent();toast('Материал сохранён')}
function openDialogueEditor(x=null){S.editing=x?.id||null;S.dialogDraft=x?.steps?structuredClone(x.steps):[{client:'',options:['','',''],correct:0,next_client:'',explanation:''}];showModal(`<div class="modal-head"><h2>${x?'Редактировать диалог':'Новый живой диалог'}</h2><button class="btn secondary" onclick="closeModal()">✕</button></div><div class="form-grid"><div class="field"><label>Раздел</label><select id="edSec"><option value="needs">Потребность</option><option value="soft">Soft</option><option value="hard">Hard</option></select></div><div class="field"><label>Тема</label><input id="edTopic"></div><div class="field full"><label>Название</label><input id="edTitle"></div><div class="field"><label>Статус</label><select id="edStatus"><option value="draft">Черновик</option><option value="published">Опубликовать</option></select></div><div class="field"><label>Кому</label><input id="edAudience" value="ALL"></div></div><div id="dialogSteps"></div><div class="actions" style="justify-content:space-between;margin-top:13px"><button class="btn secondary" onclick="addDialogStep()">+ Шаг</button><button class="btn primary" onclick="saveDialogueEditor()">Сохранить</button></div>`);$('edSec').value=x?.section||'needs';$('edTopic').value=x?.topic||'';$('edTitle').value=x?.title||'';$('edStatus').value=x?.status||'draft';$('edAudience').value=(x?.audience||['ALL']).join(', ');renderDialogSteps()}
function addDialogStep(){S.dialogDraft.push({client:'',options:['','',''],correct:0,next_client:'',explanation:''});renderDialogSteps()}
function removeDialogStep(i){if(S.dialogDraft.length===1)return;S.dialogDraft.splice(i,1);renderDialogSteps()}
function renderDialogSteps(){$('dialogSteps').innerHTML=S.dialogDraft.map((s,i)=>`<div class="card" style="margin-top:11px"><div class="toolbar"><b>Шаг ${i+1}</b><button class="btn danger" onclick="removeDialogStep(${i})">Удалить</button></div><div class="field"><label>Реплика клиента</label><textarea oninput="S.dialogDraft[${i}].client=this.value">${esc(s.client)}</textarea></div>${[0,1,2].map(j=>`<div class="field"><label>Ответ ${j+1}${j===Number(s.correct)?' ✓':''}</label><input value="${esc(s.options[j])}" oninput="S.dialogDraft[${i}].options[${j}]=this.value"><button class="btn secondary" style="margin-top:5px" onclick="S.dialogDraft[${i}].correct=${j};renderDialogSteps()">Сделать правильным</button></div>`).join('')}<div class="field"><label>Следующая реплика клиента</label><textarea oninput="S.dialogDraft[${i}].next_client=this.value">${esc(s.next_client||'')}</textarea></div><div class="field"><label>Объяснение</label><textarea oninput="S.dialogDraft[${i}].explanation=this.value">${esc(s.explanation||'')}</textarea></div></div>`).join('')}
async function saveDialogueEditor(){if(!$('edTopic').value.trim()||!$('edTitle').value.trim()){toast('Заполните тему и название');return}const row={type:'dialogue',section:$('edSec').value,topic:$('edTopic').value.trim(),status:$('edStatus').value,difficulty:'Средний',title:$('edTitle').value.trim(),payload:{steps:S.dialogDraft},audience:$('edAudience').value.split(',').map(x=>x.trim()).filter(Boolean),created_by:S.user.id,updated_at:new Date().toISOString()};if(S.editing)row.id=S.editing;const {error}=await S.sb.from('content').upsert(row);if(error){toast(error.message);return}if(row.status==='published')await notifyRecipients('Новый диалог',row.title,row.audience);closeModal();await syncAll();contentTab='library';renderContent();toast('Диалог сохранён')}
function editContent(id){const x=S.content.find(c=>c.id===id);if(!x)return;x.type==='dialogue'?openDialogueEditor(x):openCaseEditor(x.type,x)}
async function deleteContent(id){if(!confirm('Удалить материал?'))return;const {error}=await S.sb.from('content').delete().eq('id',id);if(error)toast(error.message);else{await syncAll();renderContent();toast('Материал удалён')}}

function renderAssignments(){$('page-assignments').innerHTML=`<div class="toolbar"><span class="muted small">${S.assignments.length} назначений</span><div><button class="btn primary" onclick="openAssignmentEditor()">+ Назначить</button></div></div><div class="card" style="margin-top:10px">${S.assignments.map(x=>`<div class="assignment"><div><b>${esc(x.title)}</b><div class="meta">${x.section?secName(x.section):''}${x.topic?' · '+esc(x.topic):''}${x.due?' · до '+x.due:''} · ${(x.recipients||[]).join(', ')}</div></div><div class="actions"><span class="pill">${x.target}%+</span><button class="btn danger" onclick="deleteAssignment('${x.id}')">Удалить</button></div></div>`).join('')||'<div class="muted">Назначений нет.</div>'}</div>`}
function openAssignmentEditor(){const opts=S.content.filter(x=>x.status==='published').map(x=>`<option value="${x.id}">${esc(x.title||x.question)} — ${esc(x.topic)}</option>`).join('');showModal(`<div class="modal-head"><h2>Новое назначение</h2><button class="btn secondary" onclick="closeModal()">✕</button></div><div class="form-grid"><div class="field full"><label>Название</label><input id="asTitle"></div><div class="field"><label>Материал</label><select id="asContent"><option value="">По теме</option>${opts}</select></div><div class="field"><label>Раздел</label><select id="asSec"><option value="soft">Soft</option><option value="hard">Hard</option><option value="needs">Потребность</option></select></div><div class="field"><label>Тема</label><input id="asTopic"></div><div class="field"><label>Дедлайн</label><input id="asDue" type="date"></div><div class="field"><label>Минимум %</label><input id="asTarget" type="number" value="90"></div><div class="field full"><label>Кому</label><input id="asUsers" value="ALL" placeholder="ALL или логины через запятую"></div></div><div class="actions" style="justify-content:flex-end;margin-top:13px"><button class="btn primary" onclick="saveAssignment()">Назначить и уведомить</button></div>`)}
async function saveAssignment(){const rec=$('asUsers').value.split(',').map(x=>x.trim()).filter(Boolean),row={title:$('asTitle').value.trim(),content_id:$('asContent').value||null,section:$('asSec').value,topic:$('asTopic').value.trim(),due:$('asDue').value||null,target:Number($('asTarget').value||90),recipients:rec,status:'active',created_by:S.user.id};if(!row.title){toast('Введите название');return}const {error}=await S.sb.from('assignments').insert(row);if(error){toast(error.message);return}await notifyRecipients('Новое задание',`${row.title}${row.due?' · до '+row.due:''}`,rec,'assignment');closeModal();await syncAll();renderAssignments();toast('Задание назначено')}
async function deleteAssignment(id){if(!confirm('Удалить назначение?'))return;const {error}=await S.sb.from('assignments').delete().eq('id',id);if(error)toast(error.message);else{await syncAll();renderAssignments()}}

function renderEmployees(){$('page-employees').innerHTML=`<div class="toolbar"><span class="muted small">${S.allowed.length} разрешённых логинов</span><div><button class="btn secondary" onclick="generateAllCodes()">🔐 Коды новым</button><button class="btn primary" onclick="openEmployeeEditor()">+ Добавить</button></div></div><div class="card" style="margin-top:10px">${S.allowed.map(x=>`<div class="employee-row"><div><b>${esc(x.name||x.login)}</b><div class="meta">${esc(x.login)} · ${x.role==='mentor'?'Наставник':'Сотрудник'} · ${x.claimed_user_id?'PIN создан':'первый вход не выполнен'}</div></div><div class="actions"><span class="pill ${x.active?'good':'bad'}">${x.active?'Активен':'Отключён'}</span>${x.role!=='mentor'?`<button class="btn secondary" onclick="makeCode('${x.login}')">Новый код</button>`:''}<button class="btn secondary" onclick="toggleEmployee('${x.login}',${x.active?'false':'true'})">${x.active?'Отключить':'Включить'}</button>${x.claimed_user_id&&x.role!=='mentor'?`<button class="btn danger" onclick="resetAccess('${x.login}')">Сбросить PIN</button>`:''}</div></div>`).join('')}</div>`}
function openEmployeeEditor(){const code=randCode();showModal(`<div class="modal-head"><h2>Новый сотрудник</h2><button class="btn secondary" onclick="closeModal()">✕</button></div><div class="form-grid"><div class="field full"><label>Корпоративный логин</label><input id="euLogin"></div><div class="field full"><label>Имя</label><input id="euName"></div><div class="field"><label>Роль</label><select id="euRole"><option value="employee">Сотрудник</option><option value="mentor">Наставник</option></select></div><div class="field"><label>Группа</label><input id="euGroup" value="Группа"></div><div class="field full"><label>Код первого входа</label><input id="euCode" value="${code}"></div></div><div class="actions" style="justify-content:flex-end;margin-top:13px"><button class="btn primary" onclick="saveEmployee()">Добавить</button></div>`)}
async function saveEmployee(){const login=normalizeLogin($('euLogin').value),code=$('euCode').value.trim();const {data,error}=await S.sb.rpc('mentor_upsert_allowed_user',{p_login:login,p_name:$('euName').value.trim()||login,p_role:$('euRole').value,p_group_name:$('euGroup').value.trim()||'Группа',p_active:true,p_invite_code:code||null});if(error){toast(error.message);return}closeModal();await syncAll();showCodes([[login,code]],'Передайте код сотруднику')}
async function makeCode(login){const code=randCode(),{error}=await S.sb.rpc('mentor_set_invite_code',{p_login:login,p_code:code});if(error){toast(error.message);return}showCodes([[login,code]],'Новый код первого входа')}
async function generateAllCodes(){const target=S.allowed.filter(x=>x.active&&x.role==='employee'&&!x.claimed_user_id),rows=[];for(const x of target){const code=randCode(),{error}=await S.sb.rpc('mentor_set_invite_code',{p_login:x.login,p_code:code});if(!error)rows.push([x.login,code])}if(!rows.length){toast('У всех активных сотрудников уже создан PIN');return}showCodes(rows,'Коды первого входа')}
function showCodes(rows,title){showModal(`<div class="modal-head"><h2>${esc(title)}</h2><button class="btn secondary" onclick="closeModal()">✕</button></div><p class="muted small">Код нужен только при первом входе. После него сотрудник использует свой PIN.</p><div class="card">${rows.map(r=>`<div class="employee-row"><b>${esc(r[0])}</b><span class="access-code">${esc(r[1])}</span></div>`).join('')}</div><div class="actions" style="justify-content:flex-end;margin-top:12px"><button class="btn secondary" onclick='downloadCodes(${JSON.stringify(rows)})'>⬇ CSV</button></div>`)}
function downloadCodes(rows){const csv='\uFEFFЛогин;Код первого входа\r\n'+rows.map(r=>`${r[0]};${r[1]}`).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='SkillHub_коды_первого_входа.csv';a.click();URL.revokeObjectURL(a.href)}
async function toggleEmployee(login,active){const x=S.allowed.find(u=>u.login===login);const {error}=await S.sb.rpc('mentor_upsert_allowed_user',{p_login:login,p_name:x.name,p_role:x.role,p_group_name:x.group_name,p_active:active,p_invite_code:null});if(error)toast(error.message);else{await syncAll();renderEmployees()}}
async function resetAccess(login){if(!confirm('Старый PIN перестанет работать. Продолжить?'))return;const code=randCode(),{error}=await S.sb.rpc('mentor_reset_access',{p_login:login,p_new_code:code});if(error){toast(error.message);return}await syncAll();showCodes([[login,code]],'Доступ сброшен')}

function toggleProfileMenu(){$('profileMenu').classList.toggle('hidden')}
async function enableNotifications(){$('profileMenu').classList.add('hidden');if(!('Notification'in window)){toast('Браузер не поддерживает уведомления');return}const p=await Notification.requestPermission();toast(p==='granted'?'Уведомления включены':'Разрешение не выдано')}
function showInstallHelp(){$('profileMenu').classList.add('hidden');const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);showModal(`<div class="modal-head"><h2>Установка SkillHub</h2><button class="btn secondary" onclick="closeModal()">✕</button></div>${ios?'<p>iPhone: откройте SkillHub в Safari → <b>Поделиться</b> → <b>На экран «Домой»</b> → Добавить.</p>':'<p>Android/Chrome: меню браузера → <b>Установить приложение</b> / «Добавить на главный экран».</p>'}<p class="muted small">Внутренние уведомления работают всегда при синхронизации. Полноценный push при полностью закрытом приложении требует отдельной push-настройки.</p>`)}
function showShareLink(){$('profileMenu').classList.add('hidden');const c=currentConfig(),base=location.origin+location.pathname,link=base+'?sburl='+encodeURIComponent(c.url)+'&sbkey='+encodeURIComponent(c.key);showModal(`<div class="modal-head"><h2>Ссылка для сотрудников</h2><button class="btn secondary" onclick="closeModal()">✕</button></div><p>Отправьте эту ссылку группе один раз. Она сохранит подключение к общей базе на устройстве.</p><div class="code-card" id="shareLinkText">${esc(link)}</div><div class="actions" style="justify-content:flex-end;margin-top:12px"><button class="btn primary" onclick="navigator.clipboard.writeText(document.getElementById('shareLinkText').textContent);toast('Ссылка скопирована')">Копировать</button></div><div class="hint">Anon key является публичным ключом клиентского приложения. Доступ к таблицам ограничивается политиками RLS из schema.sql.</div>`)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();S.deferredInstall=e;$('installBtn').classList.remove('hidden')});async function installApp(){if(S.deferredInstall){S.deferredInstall.prompt();await S.deferredInstall.userChoice;S.deferredInstall=null;$('installBtn').classList.add('hidden')}else showInstallHelp()}
window.addEventListener('online',()=>{updateNetwork();syncAll()});window.addEventListener('offline',updateNetwork);setInterval(()=>{if(S.user&&navigator.onLine)syncAll()},60000);document.addEventListener('click',e=>{if(!$('profileMenu').classList.contains('hidden')&&!e.target.closest('.profile')&&!e.target.closest('#profileMenu'))$('profileMenu').classList.add('hidden')});

(async function init(){updateNetwork();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(!initClient())return;const {data:{session}}=await S.sb.auth.getSession();if(session){try{await afterAuth();return}catch(e){console.warn(e)}}$('loginView').classList.remove('hidden')})();
