-- SkillHub 6.0 Free — Supabase schema
-- Run this entire file once in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.allowed_logins (
  login text primary key,
  name text not null,
  role text not null default 'employee' check (role in ('employee','mentor')),
  group_name text not null default 'Группа',
  active boolean not null default true,
  claimed_user_id uuid unique,
  invite_code_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  login text unique not null references public.allowed_logins(login) on update cascade,
  name text not null,
  role text not null check (role in ('employee','mentor')),
  group_name text not null default 'Группа',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content (
  id uuid primary key default gen_random_uuid(),
  type text not null default 'quiz' check (type in ('quiz','hardcase','dialogue')),
  status text not null default 'draft' check (status in ('draft','published')),
  section text not null check (section in ('soft','hard','needs')),
  topic text not null,
  difficulty text not null default 'Средний',
  title text not null default '',
  payload jsonb not null default '{}'::jsonb,
  audience text[] not null default array['ALL']::text[],
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assignments (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content_id uuid references public.content(id) on delete set null,
  section text,
  topic text,
  due date,
  target integer not null default 90 check (target between 0 and 100),
  recipients text[] not null default array['ALL']::text[],
  status text not null default 'active' check (status in ('active','inactive')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.attempts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  login text not null,
  created_at timestamptz not null default now(),
  section text not null,
  topic text not null,
  score numeric not null,
  type text not null default 'quiz',
  cpm integer not null default 0
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  login text not null,
  title text not null,
  body text not null,
  kind text not null default 'info',
  read boolean not null default false,
  created_at timestamptz not null default now()
);

-- The first successfully registered SkillHub user becomes the mentor automatically.
-- Employees are added later by the mentor from the interface or Excel import.

create or replace function public.current_login()
returns text language sql stable security definer set search_path=public
as $$ select login from public.profiles where id=auth.uid() $$;

create or replace function public.is_active_user()
returns boolean language sql stable security definer set search_path=public
as $$ select coalesce((select active from public.profiles where id=auth.uid()),false) $$;

create or replace function public.is_mentor()
returns boolean language sql stable security definer set search_path=public
as $$ select coalesce((select role='mentor' and active from public.profiles where id=auth.uid()),false) $$;

-- Creates a profile only for pre-approved corporate logins.
-- The first account created in a fresh project becomes the mentor.
-- Other employees must first receive a code generated by the mentor in SkillHub.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_login text := lower(trim(coalesce(new.raw_user_meta_data->>'login','')));
  v_code text := coalesce(new.raw_user_meta_data->>'invite_code','');
  a public.allowed_logins%rowtype;
  v_count bigint;
begin
  if v_login='' then
    raise exception 'LOGIN_REQUIRED';
  end if;

  select count(*) into v_count from public.allowed_logins;

  -- Fresh project: the very first account becomes the mentor.
  if v_count=0 then
    insert into public.allowed_logins(login,name,role,group_name,active,claimed_user_id)
    values(v_login,v_login,'mentor','Группа',true,new.id);
    insert into public.profiles(id,login,name,role,group_name,active)
    values(new.id,v_login,v_login,'mentor','Группа',true);
    return new;
  end if;

  select * into a from public.allowed_logins where login=v_login and active=true for update;
  if not found then
    raise exception 'LOGIN_NOT_ALLOWED';
  end if;
  if a.claimed_user_id is not null and a.claimed_user_id <> new.id then
    raise exception 'LOGIN_ALREADY_CLAIMED';
  end if;
  if a.invite_code_hash is null then
    raise exception 'INVITE_CODE_NOT_SET';
  end if;
  if crypt(v_code,a.invite_code_hash) <> a.invite_code_hash then
    raise exception 'BAD_INVITE_CODE';
  end if;
  insert into public.profiles(id,login,name,role,group_name,active)
  values(new.id,a.login,a.name,a.role,a.group_name,a.active)
  on conflict(id) do update set login=excluded.login,name=excluded.name,role=excluded.role,group_name=excluded.group_name,active=excluded.active,updated_at=now();
  update public.allowed_logins set claimed_user_id=new.id,updated_at=now() where login=a.login;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Mentor-only user management.
create or replace function public.mentor_upsert_allowed_user(
  p_login text, p_name text default null, p_role text default 'employee',
  p_group_name text default 'Группа', p_active boolean default true, p_invite_code text default null
) returns table(login text, claimed boolean)
language plpgsql security definer set search_path=public
as $$
declare v_login text:=lower(trim(p_login)); v_claimed uuid;
begin
  if not public.is_mentor() then raise exception 'FORBIDDEN'; end if;
  if v_login='' then raise exception 'LOGIN_REQUIRED'; end if;
  if p_role not in ('employee','mentor') then raise exception 'BAD_ROLE'; end if;
  insert into public.allowed_logins(login,name,role,group_name,active,invite_code_hash)
  values(v_login,coalesce(nullif(trim(p_name),''),v_login),p_role,coalesce(nullif(trim(p_group_name),''),'Группа'),p_active,
         case when p_invite_code is null or p_invite_code='' then null else crypt(p_invite_code,gen_salt('bf')) end)
  on conflict(login) do update set
    name=excluded.name, role=excluded.role, group_name=excluded.group_name, active=excluded.active,
    invite_code_hash=case when p_invite_code is null or p_invite_code='' then public.allowed_logins.invite_code_hash else crypt(p_invite_code,gen_salt('bf')) end,
    updated_at=now();
  select claimed_user_id into v_claimed from public.allowed_logins where allowed_logins.login=v_login;
  if v_claimed is not null then
    update public.profiles set name=coalesce(nullif(trim(p_name),''),v_login),role=p_role,group_name=coalesce(nullif(trim(p_group_name),''),'Группа'),active=p_active,updated_at=now() where id=v_claimed;
  end if;
  return query select v_login,(v_claimed is not null);
end;
$$;

create or replace function public.mentor_set_invite_code(p_login text,p_code text)
returns void language plpgsql security definer set search_path=public
as $$
begin
  if not public.is_mentor() then raise exception 'FORBIDDEN'; end if;
  if length(trim(p_code))<4 then raise exception 'CODE_TOO_SHORT'; end if;
  update public.allowed_logins set invite_code_hash=crypt(trim(p_code),gen_salt('bf')),updated_at=now() where login=lower(trim(p_login));
end;
$$;

create or replace function public.mentor_reset_access(p_login text,p_new_code text)
returns void language plpgsql security definer set search_path=public,auth
as $$
declare uid uuid;
begin
  if not public.is_mentor() then raise exception 'FORBIDDEN'; end if;
  select claimed_user_id into uid from public.allowed_logins where login=lower(trim(p_login));
  if uid is not null then delete from auth.users where id=uid; end if;
  update public.allowed_logins set claimed_user_id=null,invite_code_hash=crypt(trim(p_new_code),gen_salt('bf')),updated_at=now() where login=lower(trim(p_login));
end;
$$;

-- RLS
alter table public.allowed_logins enable row level security;
alter table public.profiles enable row level security;
alter table public.content enable row level security;
alter table public.assignments enable row level security;
alter table public.attempts enable row level security;
alter table public.notifications enable row level security;

-- Drop/recreate policies to make the script safely re-runnable.
do $$ declare r record; begin
 for r in select schemaname,tablename,policyname from pg_policies where schemaname='public' and tablename in ('allowed_logins','profiles','content','assignments','attempts','notifications') loop
   execute format('drop policy if exists %I on %I.%I',r.policyname,r.schemaname,r.tablename);
 end loop;
end $$;

create policy allowed_logins_mentor_select on public.allowed_logins for select to authenticated using (public.is_mentor());

create policy profiles_select on public.profiles for select to authenticated using (id=auth.uid() or public.is_mentor());

create policy content_select on public.content for select to authenticated using (
  public.is_active_user() and (
    public.is_mentor() or (status='published' and ('ALL'=any(audience) or public.current_login()=any(audience)))
  )
);
create policy content_insert on public.content for insert to authenticated with check (public.is_mentor());
create policy content_update on public.content for update to authenticated using (public.is_mentor()) with check (public.is_mentor());
create policy content_delete on public.content for delete to authenticated using (public.is_mentor());

create policy assignments_select on public.assignments for select to authenticated using (
  public.is_active_user() and (public.is_mentor() or ('ALL'=any(recipients) or public.current_login()=any(recipients)))
);
create policy assignments_insert on public.assignments for insert to authenticated with check (public.is_mentor());
create policy assignments_update on public.assignments for update to authenticated using (public.is_mentor()) with check (public.is_mentor());
create policy assignments_delete on public.assignments for delete to authenticated using (public.is_mentor());

create policy attempts_select on public.attempts for select to authenticated using (user_id=auth.uid() or public.is_mentor());
create policy attempts_insert on public.attempts for insert to authenticated with check (user_id=auth.uid() and public.is_active_user());
create policy attempts_delete on public.attempts for delete to authenticated using (public.is_mentor());

create policy notifications_select on public.notifications for select to authenticated using (login=public.current_login() or public.is_mentor());
create policy notifications_insert on public.notifications for insert to authenticated with check (public.is_mentor());
create policy notifications_update on public.notifications for update to authenticated using (login=public.current_login() or public.is_mentor()) with check (login=public.current_login() or public.is_mentor());
create policy notifications_delete on public.notifications for delete to authenticated using (public.is_mentor());

grant usage on schema public to authenticated;
grant select on public.allowed_logins to authenticated;
grant select on public.profiles to authenticated;
grant select,insert,update,delete on public.content to authenticated;
grant select,insert,update,delete on public.assignments to authenticated;
grant select,insert,delete on public.attempts to authenticated;
grant select,insert,update,delete on public.notifications to authenticated;
grant execute on function public.mentor_upsert_allowed_user(text,text,text,text,boolean,text) to authenticated;
grant execute on function public.mentor_set_invite_code(text,text) to authenticated;
grant execute on function public.mentor_reset_access(text,text) to authenticated;

-- Realtime for automatic refresh while SkillHub is open.
do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='content') then alter publication supabase_realtime add table public.content; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='assignments') then alter publication supabase_realtime add table public.assignments; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then alter publication supabase_realtime add table public.notifications; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='attempts') then alter publication supabase_realtime add table public.attempts; end if;
end $$;

-- A few safe demo materials. Replace with your own bank-approved cases.
insert into public.content(type,status,section,topic,difficulty,title,payload,audience)
select 'quiz','published','soft','Присоединение','Лёгкий','Повторное обращение',
 jsonb_build_object('question','Клиент: «Я уже третий раз обращаюсь! Сколько можно?»','answers',jsonb_build_array('Успокойтесь, пожалуйста.','Понимаю, что повторное обращение может расстроить. Давайте разберёмся, что можем сделать сейчас.','Такое бывает.','Обратитесь позже.'),'correct',1,'explanation','Присоединяемся к эмоции и переводим разговор к действию.'),array['ALL']
where not exists(select 1 from public.content where title='Повторное обращение' and topic='Присоединение');

insert into public.content(type,status,section,topic,difficulty,title,payload,audience)
select 'hardcase','published','hard','Общий','Лёгкий','Проверка актуального условия',
 jsonb_build_object('question','Вы не уверены, что помните актуальное условие продукта. Что делать?','answers',jsonb_build_array('Ответить по памяти.','Проверить актуальную внутреннюю базу знаний и только затем дать ответ.','Предположить самый частый вариант.','Спросить клиента, как было раньше.'),'correct',1,'explanation','Для Hard точность факта важнее скорости. Это демонстрационный кейс без внутренних правил банка.'),array['ALL']
where not exists(select 1 from public.content where title='Проверка актуального условия');
